parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0}),a(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((e,a)=>(0,t.jsx)("img",{src:e,"data-index":a,onClick:this.handleIndexClick,className:"active"===a?"active":"",alt:"animal thumbnail"},e))})]})}}a(s,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=s;exports.default=i;
},{}],"mD05":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=require("react/jsx-runtime");function o(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}class s extends e.Component{constructor(...e){super(...e),o(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(e,r){console.error("Error caught in the Error Boundary",e,r)}componentDidUpdate(){this.state.hasError&&setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(r.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["This listing has an error. ",(0,t.jsx)(r.Link,{to:"/",children:"Click here to go back to the home page or wait five seconds."})]}):this.props.children}}var i=s;exports.default=i;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["blue",()=>{}]);var r=t;exports.default=r;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=u;var e=require("react"),t=require("react-router"),s=a(require("./Carousel")),i=a(require("./ErrorBoundary")),r=a(require("./Modal")),o=a(require("./ThemeContext")),n=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function l(e,t,s){return t in e?Object.defineProperty(e,t,{value:s,enumerable:!0,configurable:!0,writable:!0}):e[t]=s,e}class d extends e.Component{constructor(...e){super(...e),l(this,"state",{loading:!0,showModal:!1}),l(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),l(this,"adoptAPet",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`,t=await fetch(e),s=await t.json();this.setState(Object.assign({loading:!1},s.pets[0]))}render(){if(this.state.loading)return(0,n.jsx)("h2",{children:"loading..."});const{animal:e,breed:t,city:i,state:a,description:l,name:d,images:c,showModal:u}=this.state;return(0,n.jsxs)("div",{className:"details",children:[(0,n.jsx)(s.default,{images:c}),(0,n.jsxs)("div",{children:[(0,n.jsx)("h1",{children:d}),(0,n.jsxs)("h2",{children:[e," - ",t," - ",i,", ",a]}),(0,n.jsx)(o.default.Consumer,{children:([e])=>(0,n.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",d,"!"]})}),(0,n.jsx)("p",{children:l}),u?(0,n.jsx)(r.default,{children:(0,n.jsxs)("div",{children:[(0,n.jsxs)("h1",{children:["Would you like to adopt ",d,"?"]}),(0,n.jsxs)("div",{className:"buttons",children:[(0,n.jsx)("button",{onClick:this.adoptAPet,children:"Yes"}),(0,n.jsx)("button",{onClick:this.toggleModal,children:"No"})]})]})}):null]})]})}}const c=(0,t.withRouter)(d);function u(){return(0,n.jsx)(i.default,{children:(0,n.jsx)(c,{})})}
},{"./Carousel":"Ztkr","./ErrorBoundary":"mD05","./Modal":"KnKP","./ThemeContext":"2tnM"}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:c})=>{const d=a&&a.length>0?a[0]:"http://pets-images.dev-apis.com/pets/none.jpg";return(0,s.jsxs)(e.Link,{to:`/details/${c}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:d,alt:r})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsx)("h2",{children:`${t} - ${i} - ${n}`})]})]})};var t=r;exports.default=t;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(a=>(0,t.jsx)(e.default,{name:a.name,animal:a.animal,breed:a.breed,images:a.images,location:`${a.city}, ${a.state}`,id:a.id},a.id)):(0,t.jsx)("h2",{children:"No pets were found."})});var s=r;exports.default=s;
},{"./Pet":"qepC"}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=`http://pets-v2.dev-apis.com/breeds?animal=${a}`,s=await fetch(e),o=await s.json();t[a]=o.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=n(require("./Results")),a=n(require("./ThemeContext")),l=n(require("./useBreedList")),r=require("react/jsx-runtime");function n(e){return e&&e.__esModule?e:{default:e}}const s=["cat","dog","bird","reptile","rabbit"],o=()=>{const[n,o]=(0,e.useState)("Washington, DC"),[i,u]=(0,e.useState)(""),[d,c]=(0,e.useState)(""),[h,p]=(0,e.useState)([]),[x]=(0,l.default)(i),[v,j]=(0,e.useContext)(a.default);async function m(){const e=`http://pets-v2.dev-apis.com/pets?animal=${i}&location=${n}&breed=${d}`,t=await fetch(e),a=await t.json();p(a.pets)}return(0,e.useEffect)(()=>{m()},[]),(0,r.jsxs)("div",{className:"search-params",children:[(0,r.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,r.jsxs)("label",{htmlFor:"location",children:["Location",(0,r.jsx)("input",{id:"location",onChange:e=>o(e.target.value),value:n,placeholder:"Location"})]}),(0,r.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,r.jsxs)("select",{id:"animal",value:i,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,r.jsx)("option",{}),s.map(e=>(0,r.jsx)("option",{value:e,children:e},e))]})]}),(0,r.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,r.jsxs)("select",{id:"breed",value:d,onChange:e=>c(e.target.value),onBlur:e=>c(e.target.value),children:[(0,r.jsx)("option",{}),x.map(e=>(0,r.jsx)("option",{value:e,children:e},e))]})]}),(0,r.jsxs)("label",{htmlFor:"theme",children:["Theme",(0,r.jsxs)("select",{id:"theme",value:v,onChange:e=>j(e.target.value),onBlur:e=>j(e.target.value),children:[(0,r.jsx)("option",{value:"pink",children:"Pink"}),(0,r.jsx)("option",{value:"orange",children:"Orange"}),(0,r.jsx)("option",{value:"turquoise",children:"Turquoise"}),(0,r.jsx)("option",{value:"red",children:"Red"})]})]}),(0,r.jsx)("button",{style:{backgroundColor:v},children:"Submit"})]}),(0,r.jsx)(t.default,{pets:h})]})};var i=o;exports.default=i;
},{"./Results":"r5l1","./ThemeContext":"2tnM","./useBreedList":"/HkA"}],"ffN9":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("./Details")),i=u(require("./SearchParams")),s=u(require("./ThemeContext")),d=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("green");return(0,d.jsx)(e.StrictMode,{children:(0,d.jsx)(s.default.Provider,{value:u,children:(0,d.jsxs)("div",{children:[(0,d.jsx)("header",{children:(0,d.jsx)(r.Link,{to:"/",children:(0,d.jsx)("h1",{children:"Adopt Me Please!"})})}),(0,d.jsxs)(r.Switch,{children:[(0,d.jsx)(r.Route,{path:"/details/:id",children:(0,d.jsx)(t.default,{})}),(0,d.jsx)(r.Route,{path:"/",children:(0,d.jsx)(i.default,{})})]})]})})})};var l=a;exports.default=l;
},{"./Details":"C/Dc","./SearchParams":"n0tu","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=u(require("express")),r=require("react-dom/server"),t=require("react-router-dom"),s=u(require("fs")),i=u(require("../src/app")),n=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const d=process.env.PORT||3e3,o=s.default.readFileSync("dist/index.html").toString(),a=o.split("not rendered"),l=(0,e.default)();l.use("/dist",e.default.static("dist")),l.use((e,s)=>{s.write(a[0]);const u={},d=(0,n.jsx)(t.StaticRouter,{url:e.url,context:u,children:(0,n.jsx)(i.default,{})}),o=(0,r.renderToNodeStream)(d);o.pipe(s,{end:!1}),o.on("end",()=>{s.status(u.statusCode||200),s.write(a[1]),s.end()})}),l.listen(d,()=>{console.log(`Server is listening on port ${d}`)});
},{"../src/app":"ffN9"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map